### ISSUE TITLE
Fatal error reported when building src/gpu_util.cpp on aarch64

### ISSUE THREAD

**Issue by bsansoni** [ROCm/ROCmValidationSuite#472]
Hello,

I am trying to test rocm stack on aarch64 platform.
But I got this error :    

[  4%] Building CXX object rvslib/CMakeFiles/rvslib.dir/__/src/gpu_util.cpp.o
cd /run/media/mmcblk0p2/rocm/ROCmValidationSuite/build/rvslib && /opt/rocm/hip/bin/hipcc  -DRVS_DO_TRACE -I/run/media/mmcblk0p2/rocm/ROCmValidationSuite/rvslib/. -I/run/media/mmcblk0p2/rocm/ROCmValidationSuite/rvslib/.. -I/opt/rocm/rocm_smi/include -I/opt/rocm/include -I/opt/rocm/hip  -I/usr/include/c++/9.2.0 -I/usr/include/c++/9.2.0/aarch64-fsl-linux  -fPIC -Xlinker --enable-new-dtags -fno-gpu-rdc --amdgpu-target=gfx803 --amdgpu-target=gfx900 --amdgpu-target=gfx906 --amdgpu-target=gfx908  -I/opt/rocm/hsa/include -O3 -DNDEBUG   -std=c++11 -pthread -Wl,-no-as-needed -Wall -fPIC -DRVS_OS_TYPE_NUM=0 -DBUILD_VERSION_MAJOR=3 -DBUILD_VERSION_MINOR=8 -DBUILD_VERSION_PATCH=0 -DLIB_VERSION_STRING=\"3.8.0\" -DBUILD_VERSION_STRING=\"3.8.0-3.8.0\" -o CMakeFiles/rvslib.dir/__/src/gpu_util.cpp.o -c /run/media/mmcblk0p2/rocm/ROCmValidationSuite/src/gpu_util.cpp
clang-11: warning: -Xlinker --enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
clang-11: warning: -Wl,-no-as-needed: 'linker' input unused [-Wunused-command-line-argument]
Id = 91
fatal error: error in backend: Unsupported calling convention.
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://github.com/RadeonOpenCompute/llvm-project b98349b12ffa706d0e863a3f1176b20d2a6c438b)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rvslib/CMakeFiles/rvslib.dir/build.make:63: rvslib/CMakeFiles/rvslib.dir/__/src/gpu_util.cpp.o] Error 70
make[2]: Leaving directory '/run/media/mmcblk0p2/rocm/ROCmValidationSuite/build'
make[1]: *** [CMakeFiles/Makefile2:791: rvslib/CMakeFiles/rvslib.dir/all] Error 2
make[1]: Leaving directory '/run/media/mmcblk0p2/rocm/ROCmValidationSuite/build'
make: *** [Makefile:163: all] Error 2

I put some debug in llvm (release 11.0.0) to got the CC Id in llvm/lib/Target/AArch64/AArch64ISelLowering.cpp and it corresponds to 91.
Which is AMDGPU_KERNEL.

I don't really know if the error coming from the rocmvalidation suite or llvm/clang/hip part.

What do you think ?

Thanks in advance
Benoit

**Comment by jkottiku** [comment]
Not sure if you are still on this issue ? as it has been sometime now.
But nevertheless, error seems from the compiler.
 
1. which OS were you using ?
2. can you try if you still get the same issue ? Note: Please install ROCm before trying to compile RVS.

Thanks

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @bsansoni, please reopen if you still see this issue in ROCm 6.1.0.  Thanks.
