### ISSUE TITLE
run tests without sudo

### ISSUE THREAD

**Issue by nolta** [ROCm/ROCmValidationSuite#482]
For security reasons, `sudo` is not installed on our systems. Even if it were, we cannot give code downloaded from the internet root access without a careful audit, which is infeasible for a codebase this large.

Why do all the tests require `sudo`? Many tests appear to run fine without it:

```
cd ./build/bin
./rvs -d 3
sed -i 's/sudo //' *.sh
RVS_EXE_PATH="$PWD/rvs" ./rvsqa.new.sh
```

**Comment by dipietrantonio** [comment]
I agree, I find myself in a similar situation. One should be able to run these tests without privileged access.

**Comment by jkottiku** [comment]
Hi @nolta @dipietrantonio
 
We have removed the need for sudo to running rvs tests sometime back.
Please try with the latest RVS package or code base.

Thanks and Regards,
Junaid
