### ISSUE TITLE
don't vendor dependencies

### ISSUE THREAD

**Issue by haampie** [ROCm/ROCmValidationSuite#502]
Can you please make cmake stop downloading & building dependencies?

- It doesn't work on air gapped build nodes.
- It is unsafe because there is no checksum validation
- It's not reproducible because you're building arbitrary versions (the `master` branch...).

Please just use find_package, find_library. At the very least make it possible to disable vendored dependencies.

**Comment by jkottiku** [comment]
Hi @haampie 

Yes, agree with you on this. We have remove download and build of yaml-cpp with this [commit](https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/commit/bbd771f5dcd0bc0b53a57f8a66191a3284f295ee).

Please try with latest master code base.

Thanks and Regards,
Junaid

**Comment by manoj-freyr** [comment]
@haampie we are using yaml-cpp with find_package() .
Closing this issue
