### ISSUE TITLE
rvsqa.new.sh path does not work

### ISSUE THREAD

**Issue by gggh000** [ROCm/ROCmValidationSuite#522]
From
https://github.com/ROCm-Developer-Tools/ROCmValidationSuite
I see following:
...
Running version pre-complied and packaged with ROCm release
sudo <rocm_installed_folder>/rvs/rvs -d 3
eg/- sudo /opt/rocm-4.0.0/rvs/rvs -d 3
sudo <rocm_installed_folder>/rvs/rvsqa.new.sh
eg/- sudo /opt/rocm-4.0.0/rvs/rvsqa.new.sh 
Similarly, you can run all tests as mentioned in "rvsqa.new.sh" script, present at "testscripts/rvsqa.new.sh"

the rvs -d 3 appears to run fine but running rvsqa.new.sh runs into path issue:

[root@u1804 rvs]# "testscripts/rvsqa.new.sh"
=========================Starting RVS Suite=========================
===========================gpup=========================
sudo: ./gpup.new.sh: command not found
===========================gst=========================
sudo: ./gst.new.sh: command not found
===========================iet=========================
sudo: ./iet.new.sh: command not found
===========================pebb=========================
sudo: ./pebb.new.sh: command not found
===========================peqt=========================
sudo: ./peqt.new.sh: command not found
==========================pesm=========================
sudo: ./pesm.new.sh: command not found
===========================pqt=========================
sudo: ./pqt.new.sh: command not found
===========================memory=========================
sudo: ./rvs-mem.sh: command not found
=========================RVS Suite completed, check txt for output============
[root@u1804 rvs]#

**Comment by superzerg** [comment]
I got the same problem installing from source.
As the quick fix you can:
```sh
cd <rocm_installed_folder>/rvs/testscripts
sudo ln -s ../rvs .
sudo ln -s ../conf .
```
and now `sudo ./rvsqa.new.sh` works :-)

**Comment by ppanchad-amd** [comment]
@gggh000 Is your issue resolved? If so, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@gggh000 Closing ticket. Please re-open if you are still seeing the issue with ROCm 6.2. Thanks!
