### ISSUE TITLE
Issues with install 

### ISSUE THREAD

**Issue by JBBIntel** [ROCm/ROCmValidationSuite#551]
Hello. I am trying to install RVS on an ubuntu machine with an MI210. It is part of a cluster. 

I used these commands;
cmake  -DROCM_PATH=/opt/rocm -DCMAKE_INSTALL_PREFIX=/opt/rocm -DCMAKE_PACKAGING_INSTALL_PREFIX=/opt/rocm ./ -B./build
make -C ./build
cd ./build
make package

When I get to the make package step, I get this error;
CPack: - Install project: rocm-validation-suite []
CMake Error at /nfs/site/home/jbberry/amd/ROCmValidationSuite/build/rvs/cmake_install.cmake:101 (file):
  file problem creating directory: /rvs
Call Stack (most recent call first):
  /nfs/site/home/jbberry/amd/ROCmValidationSuite/build/cmake_install.cmake:107 (include)

Looking a the indicated cmake file, it appears that it has somehow lost the packaging prefix, so it is trying to create /rvs, and it does not have the permissions. I altered the file to hard-code the packaging prefix, but it can't create /opt/rocm/rvs either. I tried running with sudo, but then it can't create files in the rundir. 

I am wondering how this could possibly have worked for anyone. Do we have our permissions set in a non-standard fashion?

**Comment by jkottiku** [comment]
ROCm should be installed in the machine at path **/opt/rocm** before you try to build RVS. Hope you have already installed ROCm ? 
Also please note there is typo in the command. Use `cmake -DROCM_PATH=/opt/rocm -DCMAKE_INSTALL_PREFIX=/opt/rocm -DCMAKE_PACKAGING_INSTALL_PREFIX=/opt/rocm -B ./build` instead.

**Comment by manoj-freyr** [comment]
Closing the issue as there is no update after the suggested fix. Please open if you see any issue in running cmake or make
