### ISSUE TITLE
JSON output format syntactically correct.

### ISSUE THREAD

**Issue by avikram2** [ROCm/ROCmValidationSuite#638]
When I run the pebb module with the -j flag, the tool dumps the bandwidth information in JSON format to a json file in /var/tmp, titled with the system time. The issue is that the file is not syntactically correct JSON, and so I cannot load the file with pythons json library, nor with pandas.read_json function. 

Please suggest how to address this issue, as I plan on running the pebb module continuously and want 'a dashboard' of the results.

**Comment by jkottiku** [comment]
Hi @avikram2 
Thanks for reporting issue. Was able to reproduce the issue in pebb json file. Expect the fix soon. Will post here once its merged to mainline,

**Comment by avikram2** [comment]
@jkottiku were you able to resolve the issue?

**Comment by jkottiku** [comment]
@avikram2 Couldn't complete yet, even though analyzed the issue and started the work sometime back but it got sidelined. Changes involve overall json logging design, json file structure and would impact other modules as well not just pebb. Will resuming it this week & keep you posted here.

**Comment by manoj-freyr** [comment]
@avikram2 please check with latest RVS master. Changes to fix the parsing issue are in place.  Verified with jq parser on Linux.

**Comment by manoj-freyr** [comment]
Closing as the issue was fixed in master. 
Reopen if you see related issues
