### ISSUE TITLE
[Issue]: action_7 Babel memory stress test crashed

### ISSUE THREAD

**Issue by songrui2009** [ROCm/ROCmValidationSuite#797]
### Problem Description

[RESULT] [  1093.214031] Action name :action_7
[RESULT] [  1093.214788] Module name :babel
[INFO  ] [  1093.214807] Missing 'device_index' key.
[RESULT] [  1093.214885] [action_7] [GPU:: 9988] Starting the Babel memory stress test
Running kernels 5000 times
Precision: double
Array size: 268.4 MB (=0.3 GB)
Total size: 805.3 MB (=0.8 GB)
elements per lane 2
chunks per block 2
block count 8192
Using HIP device Radeon RX 7900 XT
Driver: 60241133
pciBusID: 10
Error: invalid device function

### Operating System

ubuntu 24.04

### CPU

AMD Ryzen 5 3600 6-Core Processor

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

/opt/rocm/bin/rvs -d 3

**Comment by jkottiku** [comment]
Babel test was not enabled in AMD Radeon RX 7900 XT (Navi-31). With [commit](https://github.com/ROCm/ROCmValidationSuite/commit/d9be65ec45c3cbe5236f9f9349283693ed4bf512) the test is now supported in this platform as well.
