### ISSUE TITLE
[Issue]: Unable to compile version 6.3, rror: undefined reference

### ISSUE THREAD

**Issue by RandUser123sa** [ROCm/ROCmValidationSuite#865]
### Problem Description

I'm trying to compile the project but receive error:
[  4%] Built target rvs_userguide
[ 31%] Built target rvslib
[ 32%] Linking CXX executable ../bin/rvs
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: rocblas_gemm_strided_batched_ex3
>>> referenced by ../bin/librvslib.so.0.0.60300

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: rocblas_gemm_ex3
>>> referenced by ../bin/librvslib.so.0.0.60300
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
failed to execute:/opt/rocm/lib/llvm/bin/clang++ --driver-mode=g++ --hip-link  -fPIC -fno-gpu-rdc -I/opt/rocm/include -O3 -DNDEBUG -Wl,--enable-new-dtags,--rpath,\$ORIGIN/../lib -Xlinker --dependency-file=CMakeFiles/rvs.dir/link.d CMakeFiles/rvs.dir/src/rvs.cpp.o -o "../bin/rvs" -L/mnt/arch/rocm/rocm-build/build/rocmvalidationsuite/rvs -L/mnt/arch/rocm/rocm-build/build/rocmvalidationsuite/rvslib -L/opt/rocm/lib -Wl,-rpath,/mnt/arch/rocm/rocm-build/build/rocmvalidationsuite/rvs\:/mnt/arch/rocm/rocm-build/build/rocmvalidationsuite/rvslib\:/opt/rocm/lib\:/mnt/arch/rocm/rocm-build/build/rocmvalidationsuite/bin\: ../bin/librvslib.so.0.0.60300 -lrocblas -lrocm_smi64 -lhsakmt -lhsa-runtime64 -ldl -lpthread -lpci -lyaml-cpp -lhiprand -lhipblaslt
make[2]: *** [rvs/CMakeFiles/rvs.dir/build.make:102: bin/rvs] Error 1
make[1]: *** [CMakeFiles/Makefile2:686: rvs/CMakeFiles/rvs.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

### Operating System

Slackware 15.0 x86_64

### CPU

AMD Ryzen 7 3800X 8-Core Processor

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.3.0

### ROCm Component

ROCmValidationSuite

### Steps to Reproduce

Here is the configuration params:

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/amdclang \
    -D CMAKE_C_COMPILER=/opt/rocm/llvm/bin/amdclang \
    -D CMAKE_INSTALL_PREFIX=/opt/rocm \
    -D AMDGPU_TARGETS="gfx900;gfx906:xnack-;gfx908:xnack-;gfx90a;gfx942;gfx1010;gfx1012;gfx1030;gfx1100;gfx1101;gfx1102;gfx1151;gfx1200;gfx1201" \
    -D GPU_TARGETS="gfx900;gfx906:xnack-;gfx908:xnack-;gfx90a;gfx942;gfx1010;gfx1012;gfx1030;gfx1100;gfx1101;gfx1102;gfx1151;gfx1200;gfx1201" \
    -D RVS_BUILD_TESTS=OFF \
    -D RVS_ROCBLAS=0 \
    -D RVS_ROCMSMI=0 \
    ..

cmake --build .

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.14
Runtime Ext Version:     1.6
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 3800X 8-Core Processor 
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 7 3800X 8-Core Processor 
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4560                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    32787696(0x1f44cf0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    32787696(0x1f44cf0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32787696(0x1f44cf0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32787696(0x1f44cf0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1100                            
  Uuid:                    GPU-6e99eccb20090e4e               
  Marketing Name:          AMD Radeon RX 7900 XTX             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29772(0x744c)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2482                               
  BDFID:                   3072                               
  Internal Node ID:        1                                  
  Compute Unit:            96                                 
  SIMDs per CU:            2                                  
  Shader Engines:          6                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 462                                
  SDMA engine uCode::      24                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1100         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by harkgill-amd** [comment]
Hi @RandUser123sa, I wasn't able to reproduce this linking error using either the `master` or `rocm-6.3.0` branches with both the build instructions in the readme and your own steps. 

From the error message, it looks like `ld.lld` can't find symbols for `rocblas_gemm_ex3` and `rocblas_gemm_strided_batched_ex3`. These symbols should be linked from `librocblas.so` under `/opt/rocm/lib`. Could you please confirm if the lib is present and correctly versioned with the output of `ls /opt/rocm/lib | grep librocblas`?

**Comment by RandUser123sa** [comment]
Hi @harkgill-amd, yes I compile and use rocBLAS but without Tensile for the moment:

ls -la /opt/rocm/lib | grep librocblas
lrwxrwxrwx  1 root root         15 Dec 12 13:20 librocblas.so -> librocblas.so.4*
lrwxrwxrwx  1 root root         23 Dec 12 13:20 librocblas.so.4 -> librocblas.so.4.3.60300*
-rwxr-xr-x  1 root root   59236656 Dec 12 13:03 librocblas.so.4.3.60300*

**Comment by RandUser123sa** [comment]
I confirm, the problem is in rocBLAS if is compiled without Tensile library. I now compile rocBLAS with Tensile and everything is working like a charm!
